# Generated by Django 3.1.1 on 2020-09-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fighter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='growth',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='weight',
            field=models.FloatField(),
        ),
    ]
