# Generated by Django 3.1.1 on 2020-09-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200910_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
