# Generated by Django 3.1.1 on 2020-10-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_federation'),
    ]

    operations = [
        migrations.AddField(
            model_name='federation',
            name='directions',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
