# Generated by Django 3.1.1 on 2020-10-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_news_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='publication_date',
        ),
    ]
