# Generated by Django 3.1.1 on 2020-10-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_news_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publication_date',
            field=models.DateField(null=True),
        ),
    ]
