# Generated by Django 3.1.1 on 2020-10-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_news_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='growth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
