# Generated by Django 3.1.1 on 2020-10-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201008_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
